import type { StrandPlayer } from "./types";

export const TEAM_SIZE = 10;

export const STRAND_PLAYERS: StrandPlayer[] = [
  {
    id: "andrew-mager",
    name: "Andrew Mager",
    nickname: "BLADE",
    initials: "AM",
    email: "magerag1@gmail.com",
    blurb: "First-timer with low-handicap firepower and a calm, efficient game.",
    grintId: null,
    tags: ["rookie", "low-handicap", "calm"],
    estimatedIndex: 9,
  },
  {
    id: "brett-comfort",
    name: "Brett Comfort",
    nickname: "BRETT",
    initials: "BC",
    email: "brettcomfort1@gmail.com",
    blurb: "New dad, Clemson loyalist, and permanently down-for-whatever.",
    grintId: "2350937",
    grintUsername: "brettcomfort1@gmail.com",
    location: "La Mirada, CA",
    tags: ["vibes", "team-player"],
  },
  {
    id: "brian-kerns",
    name: "Brian Kerns",
    nickname: "KERNS",
    initials: "BK",
    blurb: "New to the Strand field — replacing Eric Therrien for Gamble Sands 2026.",
    grintId: null,
    tags: ["replacement", "unknown-form"],
    estimatedIndex: 16,
  },
  {
    id: "fred-geisinger",
    name: "Fred Geisinger",
    nickname: "FRED",
    initials: "FG",
    email: "fred.geisinger@gmail.com",
    blurb: "Chief planner, spreadsheet artist, and annual guardian of tee times, dinners, and logistics.",
    grintId: "363887",
    grintUsername: "fgeisinger22",
    location: "Encinitas, CA",
    tags: ["planner", "low-handicap", "steady"],
  },
  {
    id: "jack-groot",
    name: "Jack Groot",
    nickname: "JACK",
    initials: "JG",
    email: "jack.l.groot@gmail.com",
    blurb: "First trip, zero rookie energy. Midwest golfer with instant chemistry.",
    grintId: "678772",
    grintUsername: "jgroot35",
    location: "Palatine, IL",
    tags: ["rookie", "improving", "reliable"],
  },
  {
    id: "jason-olson",
    name: "Jason Olson",
    nickname: "JASON",
    initials: "JO",
    email: "jason.r.olson@gmail.com",
    blurb: "Steady, reliable, easygoing, and exactly the kind of rock-solid presence every golf trip needs.",
    grintId: "588935",
    grintUsername: "olsonj12",
    location: "Van Nuys, CA",
    tags: ["steady", "rock-solid"],
  },
  {
    id: "jordan-brodbeck",
    name: "Jordan Brodbeck",
    nickname: "GORD",
    initials: "JB",
    email: "jydeezy465@gmail.com",
    blurb: "Heart-and-soul guy with elite vibes, strong low-net energy, and executive-committee usefulness.",
    grintId: "218633",
    grintUsername: "JordanBrodbeck",
    location: "Manhattan Beach, CA",
    tags: ["low-net", "match-play", "leader"],
  },
  {
    id: "justin-uribe",
    name: "Justin Uribe",
    nickname: "J-BONE",
    initials: "JU",
    email: "uribe.justin@gmail.com",
    blurb: "Former baseball standout turned golf alpha and fierce competitor.",
    grintId: "3575329",
    grintUsername: "ureebs",
    location: "Los Angeles, CA",
    tags: ["competitor", "athlete", "low-handicap"],
  },
  {
    id: "kevin-gordon",
    name: "Kevin Gordon",
    nickname: "KEV",
    initials: "KG",
    email: "gordon.kevin.g@gmail.com",
    blurb: "Bay Area local with a sneakily nasty golf game and supreme post-round chill.",
    grintId: "4087843",
    grintUsername: "kevin.x.gordon",
    location: "East Islip, NY",
    tags: ["sneaky", "match-play", "low-handicap"],
  },
  {
    id: "matt-onorato",
    name: "Matt Onorato",
    nickname: "MATTY O.",
    initials: "MO",
    email: "mattonorato@gmail.com",
    blurb: "Winningest man in Strand history with high style points and full-send commitment.",
    grintId: "1335470",
    grintUsername: "MattyOoo",
    location: "Charlotte, NC",
    tags: ["champion", "clutch", "experience"],
  },
  {
    id: "matt-schroeder",
    name: "Matt Schroeder",
    nickname: "TONY SCHROE",
    initials: "MS",
    email: "matt.c.schroeder@gmail.com",
    blurb: "Walking rulebook, serious golf purist, and trip organizer with by-the-book instincts.",
    grintId: "651324",
    grintUsername: "tonyschroe",
    location: "Redondo Beach, CA",
    tags: ["purist", "organizer", "steady"],
  },
  {
    id: "matt-wixted",
    name: "Matt Wixted",
    nickname: "WIX",
    initials: "MW",
    email: "mwixted1@gmail.com",
    blurb: "Natural athlete, former Most Improved, and the creative hand behind the yearly Strand look.",
    grintId: "1812465",
    grintUsername: "bpfsy57k2y@privaterelay.appleid.com",
    location: "Anaheim, CA",
    tags: ["athlete", "improving", "creative"],
  },
  {
    id: "nick-kane",
    name: "Nick Kane",
    nickname: "KANE",
    initials: "NK",
    email: "nskane87@gmail.com",
    blurb: "Southern flavor, golf obsession, and a swing built through pure stubbornness.",
    grintId: "929053",
    grintUsername: "Kaner87",
    location: "Hermosa Beach, CA",
    tags: ["grinder", "southern"],
  },
  {
    id: "nick-sprowls",
    name: "Nick Sprowls",
    nickname: "NICK",
    initials: "NS",
    email: "nsprowls17@gmail.com",
    blurb: "Resident funny man with emotional-volatility major-championship energy.",
    grintId: "2962924",
    grintUsername: "nsprowls17",
    location: "Hermosa Beach, CA",
    tags: ["clutch", "volatile", "fun"],
  },
  {
    id: "pat-morse",
    name: "Pat Morse",
    nickname: "P-MO",
    initials: "PM",
    email: "patrick.k.morse@gmail.com",
    blurb: "Founding Pounder and proven bringer of good vibes, good company, and timely golf.",
    grintId: "1193408",
    grintUsername: "P-Mo24",
    location: "Redondo Beach, CA",
    tags: ["founder", "vibes", "timely"],
  },
  {
    id: "rhett-fahrney",
    name: "Rhett Fahrney",
    nickname: "RHETT",
    initials: "RF",
    email: "rfahrney7@gmail.com",
    blurb: "Not always textbook, often dangerous. Great hands and enough shotmaking chaos to keep every match alive.",
    grintId: "1392795",
    grintUsername: "rfahrney7",
    location: "La Quinta, CA",
    tags: ["shotmaker", "chaos", "dangerous"],
  },
  {
    id: "ryan-darcy",
    name: "Ryan Darcy",
    nickname: "D'ARCY",
    initials: "RD",
    email: "darcy024@gmail.com",
    blurb: "Innovative golf mind, former simulator-business leader, and proven captain.",
    grintId: "1162766",
    grintUsername: "darcyryan",
    location: "Manhattan Beach, CA",
    tags: ["captain", "champion", "strategist"],
  },
  {
    id: "sam-blonski",
    name: "Sam Blonski",
    nickname: "BLONSKI",
    initials: "SB",
    email: "samuelmblonski@gmail.com",
    blurb: "Detroit distance, Manhattan Beach energy, and effortless fit with the crew.",
    grintId: "1572836",
    grintUsername: "SamBlonski",
    location: "Plymouth, MI",
    tags: ["distance", "fit"],
  },
  {
    id: "shaun-eipper",
    name: "Shaun Eipper",
    nickname: "SHAUN",
    initials: "SE",
    email: "shauneipper@gmail.com",
    blurb: "Easy energy, strong hang, quietly competitive, and one of those guys who makes the trip feel complete.",
    grintId: "1240826",
    grintUsername: "Mustard Seeds",
    location: "Redondo Beach, CA",
    tags: ["quiet", "competitive", "glue"],
  },
  {
    id: "tim-hummel",
    name: "Tim Hummel",
    nickname: "HUMMEL",
    initials: "TH",
    email: "thummel8@gmail.com",
    blurb: "Utility player of the trip. Helpful, funny, grill-capable, and always ready to keep the crew moving.",
    grintId: "758827",
    grintUsername: "thummel8",
    location: "Hawthorne, CA",
    tags: ["utility", "grill", "team-player"],
  },
];

export const ERIC_THERRIEN: StrandPlayer = {
  id: "eric-therrien",
  name: 'Eric "Blaze" Therrien',
  nickname: "BLAZE",
  initials: "ET",
  blurb: "Out of the 2026 Strand field — replaced by Brian Kerns.",
  grintId: "328084",
  grintUsername: "etherrien1004",
  location: "Chicago, IL",
  tags: ["out"],
  out: true,
};